### ISSUE TITLE
如何在NavBar组件内添加react 路由

### ISSUE THREAD

**Issue by whevether** [amazeui/amazeui-touch#101]
问题描述：
NavBar导航的数据都写在data里面,但是react 一般都是 <IndexLink></IndexlLink>这中写法配合    route  路由写的;  这个组件该怎么配置导航路由呢;

**Comment by lwxyfer** [comment]
增加属性：
```
component: Link,
to: '/',  // 你的路由
```

有些未直接写在文档的 API 可以看 kitchen-sink 里的代码 或者项目源代码
