### ISSUE TITLE
modal关闭问题

### ISSUE THREAD

**Issue by aaronyoung001** [amazeui/amazeui-touch#105]
使用了官网api文档中提供的 closeViaBackdrop 属性，就是点击遮罩层关闭。
但是chrome下报 Warning: Unknown prop `closeViaBackdrop` on <div> tag. Remove this prop from the element

 amazeui-touch 版本为 ^1.0.0-rc.2

用法如下：

`<Modal
                    role="loading"
                    closeViaBackdrop={true}
                    isOpen={this.props.isLoging}
                >
`

**Comment by minwe** [comment]
在 https://github.com/amazeui/amazeui-touch/commit/abec9314f56d0b75cf1e7c7815be630e759a987d 中已经处理。
