### ISSUE TITLE
list.item组件是否改成可以nested支持node？

### ISSUE THREAD

**Issue by medz** [amazeui/amazeui-touch#108]
说实话，因为我需要
<img width="194" alt="qq20161012-0 2x" src="https://cloud.githubusercontent.com/assets/5564821/19333926/062a40a4-912b-11e6-8802-83b3931e3d75.png">
这样的效果，自己写已经呵呵了，重复造轮子不想呀。你们的list.item本身可以直接支持，但是，，但是。。希望能自定义后面的nested DOM.

**Comment by minwe** [comment]
现在的 `nested` 属性只是表明里面嵌套的是什么类型的组件，作为应用样式的钩子，里面的组件结构还是需要自己组织。

**Comment by minwe** [comment]
```html
<List>
  <List.Item
    media={<img style={{borderRadius: '50%'}} width="48" src="http://lorempixel.com/160/160/people/" />}
    title={<div>标题 <small style={{display: 'block', color: '#888'}}>标题下方文字</small></div>}
    after={<Badge amStyle='secondary'>关注</Badge>}
  />
</List>
```

这样差不多和你的需求一致。
