### ISSUE TITLE
TabBar.Item组件不支持自定义图标～

### ISSUE THREAD

**Issue by medz** [amazeui/amazeui-touch#109]
该组件不支持自定义图标，只支持内置的那几个，明显是不符合正常开发需要的呀～
 我说的是自定义图标node。
完全可以简单的修改来达到自定义图标的目的。。。哎～你们要坑死人呀～

**Comment by beetle2013** [comment]
可以使用 https://icomoon.io/app/#/select/font

**Comment by medz** [comment]
@beetle2013 我说的是比如svg，你这个不能自己设计svg来玩，还要写css～多麻烦，考虑下纯oo开发嘛～比如我想用这个做一次三端的东西，不可能还要自己去做字体～都是画完svg就完事。
