### ISSUE TITLE
OffCanvas关闭问题？

### ISSUE THREAD

**Issue by liangglei** [amazeui/amazeui-touch#110]
在调用NavBar里的OffCanvasTrigger的ref时，老是报undefined错误，无法调用close()函数，通过程序关闭OffCanvas

**Comment by FourOnes** [comment]
@liangglei 你问题解决了吗？目前也遇到这个问题。不知该怎么获取OffCanvasTrigger。

**Comment by liangglei** [comment]
@FourOnes 我是换了种方式解决的，this.refs.oct1.close();就可以关闭了，给你参考一下
  render(){
       let headerMenu= (<OffCanvasTrigger
            ref="oct1"
            offCanvas={this.renderOC()}
          >
         <Button amStyle="primary" style={{paddingLeft:0,color:'#f2f2f2'}}><Icon name="bars" />打开左侧栏</Button>
         </OffCanvasTrigger>);
        return (<NavBar
          amStyle="primary"
          title= {headerMenu}
          titleOnLeft
        />)

   }
