### ISSUE TITLE
被你们的转场动画坑死了，transition，回出发需要删除的组件的render事件。

### ISSUE THREAD

**Issue by medz** [amazeui/amazeui-touch#111]
## 问题描述

在使用amazeui-touch支持的转场动画时候发现一个神奇的事情，就是，当转场的时候会触发react删除的组件的render事件，也就是说，在特定情况下，使用react-redux这种数据流管理机，会触发旧的组件的render事件，导致react报错。看了代码，要改市转场动画组件的bug，再插入新的component后，两个组件都在列表中，导致之前的组件需要重新渲染一次。而且，如果我将获取的方法在componentUpdateMout之类的方法内，就会重新请求服务器了。。。大哥些，你们组件好久没维护了，速度改改呀。。。。

**Comment by minwe** [comment]
转场动画基于 ReactCSSTransitionGroup 实现，如果结合其他组件时候时遇到问题，不要使用即可。
