### ISSUE TITLE
為何amaze ui touch 的kitchen sink 例子在iOS上，底部tabbar和navbar是可以隨意上下移動？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#116]
為何amaze ui touch 的kitchen sink 例子在iOS safari 上，整個頁面連底部tabbar都可以上下移動？

稍微大動作上下拖動，然後整個頁面也跟著移動，不像是spa。試了mint ui 和 ant ui 的 kitchen sink，無此問題。

這是為什麼？@minwe @lwxyfer 謝謝

**Comment by kdenz** [comment]
在css里面加position: fixed 还有bottom: 0 好像就好了

**Comment by lwxyfer** [comment]
safari 上网页都是这样的， 你应该是看到的黑色背景，修改 body 的 `background` 你会看到变化的。
