### ISSUE TITLE
【求救】不能使用自己的Fork？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#117]
@minwe @lwxyfer @windcbf 
求救！因为要用自订icon的关系，所以fork了这library，然后修改了_user.scss

然后我在package.json里面修改了dependency为自己fork的url
![image](https://cloud.githubusercontent.com/assets/12795428/20908607/f31010d0-bb90-11e6-8012-33071931cb42.png)

可是build的时候出事了
![image](https://cloud.githubusercontent.com/assets/12795428/20908520/82345786-bb90-11e6-85f6-394d5aaad222.png)

网上找了好久原因都无果，自己看了一下library，发现lib的folder不见了，只有dist
![image](https://cloud.githubusercontent.com/assets/12795428/20908666/547bc102-bb91-11e6-936b-8e05ea4a4d2e.png)

现在我该怎么办？还打算试试透过Github 部署Continuous Deployment呢，可是现在连在local也build不好

我的project是基于amt-starter-kit的，不知道这问题怎么破？谢谢！！！

**Comment by medz** [comment]
你不会写新的style文件呀～。。。

**Comment by kdenz** [comment]
@medz

怎麼寫才能能確保 _user.scss 不會被amazeui touch master影響？: )

**Comment by medz** [comment]
@kdenz 你的需求就是自定义图标对吧？你可以用第三发图标，甚至svg呗～而且，为什么你一点要和amaze的图标class重名么？比如，除非你想修改amaze的图标才需要～你的style文件覆盖amazeui的样式就行了呀～

**Comment by lwxyfer** [comment]
如果内置的不能满足需求：
1. 只有少量自定义的图表，可以直接引入图标的图片
2. 有很多图标的需求可以 clone amazeui-touch， 修改 src/scss/_user.scss ， 然后打包，复制dist文件到你的项目中。

**Comment by kdenz** [comment]
@medz 是想减少多余的东西~ 覆盖了但要在node_modules/amazeui-touch里覆盖才行，我是想在project style文件夹里进行覆盖，可是不行~
@lwxyfer  看来唯有如此，好的謝謝！！
