### ISSUE TITLE
组件Modal问题

### ISSUE THREAD

**Issue by fakediulei** [amazeui/amazeui-touch#120]
## 问题描述

渲染组件的时候，控制台报这个错：
amazeui.touch.min.js:6 Uncaught TypeError: Cannot read property 'appendChild' of null(…)

组件代码段：
<Modal isOpen={true} onDissmiss={()=>this.closeModal()} title="modal标题">
				modal内容
				</Modal>

## 产生环境

- **设备及型号：**（PC chrome）
- **操作系统及版本：**（windows 10）

**Comment by lwxyfer** [comment]
你可以将你的代码说的更清楚些
