### ISSUE TITLE
List.item如何添加新元素，以及控制布局

### ISSUE THREAD

**Issue by zuoxu91** [amazeui/amazeui-touch#121]
目前项目中需要List的内容更加丰富，比如包含服务评星，评价标签，距离。请问应该怎么增加List.item，以及控制其在List中的布局
![2017-01-16_11-51-43](https://cloud.githubusercontent.com/assets/20529125/21970567/720abacc-dbe2-11e6-908d-f5f8f72650a4.jpg)

**Comment by lwxyfer** [comment]
这个需要你在 List 上进行自定义的扩展了，因为默认是没有这个结构的。

**Comment by zuoxu91** [comment]
谢谢！可以大致说下操控那个位置么，我之前看了下关联的CSS，没有找到。水平有限哈，万分感谢！！


来自 魅族 MX5

-------- 原始邮件 --------
发件人：LW <notifications@github.com>
时间：周五 1月20日 10:46
收件人：amazeui/amazeui-touch <amazeui-touch@noreply.github.com>
抄送：zuoxu91 <zuoxu91@qq.com>,Author <author@noreply.github.com>
主题：Re: [amazeui/amazeui-touch] List.item如何添加新元素，以及控制布局 (#121)

**Comment by lwxyfer** [comment]
就是你可以复制 List 组件的代码，然后进行修改。或者你想的话，也可以使用 Grid 完全写一个你的需求的组件。
