### ISSUE TITLE
使用轮播时不断报错

### ISSUE THREAD

**Issue by morehardy** [amazeui/amazeui-touch#125]
## 问题描述
使用轮播组件之后,每次图片自动切换都会报错.
## 产生环境

- **mac pro**
- **操作系统及版本：macOS sierra 10.12.6**
- **浏览器及版本：Chrome v61.0.3163.100**
- **问题截图/录屏：**
<img width="740" alt="2017-11-06 3 19 47" src="https://user-images.githubusercontent.com/30150764/32445238-b4add056-c2ca-11e7-8615-0288ed9d9860.png">

**Comment by sxwailyc** [comment]
这项目应该已经充坑了吧，一年多没更新了
