### ISSUE TITLE
请问使用Webpack时，需要额外配置吗？

### ISSUE THREAD

**Issue by daCapricorn** [amazeui/amazeui-touch#14]
使用webpack打包，样式文件未引入。测试material ui则OK。请问需要额外配置吗？

**Comment by minwe** [comment]
material ui 样式是写在 JS 里的吧。

个人不喜欢在 JS 文件里 `require` CSS 文件，JS 和 CSS 打包是分开，需要单独处理。

**Comment by daCapricorn** [comment]
加入`{ test: /\.css$/,loader: 'style-loader!css-loader' }`后成功
