### ISSUE TITLE
安装 Amaze UI Touch的命令不规范

### ISSUE THREAD

**Issue by monkey59** [amazeui/amazeui-touch#15]
### 文档错误

[安装 Amaze UI Touch](http://t.amazeui.org/#/docs?_k=nci6pg)
> npm install --save-dev amazeui-touch

这里是否用--save更为妥当
> npm install --save amazeui-touch

**Comment by minwe** [comment]
开发环境才需要下载依赖，生产环境都是打包后的文件， 无须下载。

对于前端的应用场景，放在你开发依赖里没问题。

后端渲染目前还没有专门做支持，另当别论。
