### ISSUE TITLE
gulp启动不了

### ISSUE THREAD

**Issue by zhuzhengwen1983** [amazeui/amazeui-touch#17]
![image](https://cloud.githubusercontent.com/assets/846381/11875876/cb28d57e-a521-11e5-9d22-54e0d9d76ea6.png)

**Comment by minwe** [comment]
Node 版本和 npm 版本是多少？

看样子是 babe 没有载入，你目录下面有 package.json 这个文件吗？

**Comment by zhuzhengwen1983** [comment]
我在win7 下 
node 4.2.3
npm 3.5.2

没有package.json文件，有gulpfile.babel.js和webpack.config.js

**Comment by minwe** [comment]
重新下载或者 clone 源码，如果不知道里面的文件是干嘛的，不要随便删除文件。

**Comment by zhuzhengwen1983** [comment]
谢谢minwe， 我晚上再试试。
