### ISSUE TITLE
amaze ui touch安卓机实测在UC等浏览器上会错版，同时动画卡顿

### ISSUE THREAD

**Issue by dhj2020** [amazeui/amazeui-touch#18]
amaze ui touch在安卓机上用UC等浏览器测试时会错版，同时动画卡顿，望能尽快改进这个问题

**Comment by includeleec** [comment]
one puls two也有这个情况.. 悲剧 不敢用了

**Comment by yangzj1992** [comment]
MX5 PRO打开amaze ui touch在微信和UC上都有无法滑动的问题。

**Comment by minwe** [comment]
错版是 flexbox 的兼容性问题，参考 #12。

至于卡顿，貌似也是这些坑爹浏览器的专属问题，各位如果看到在安卓 UC 等浏览器上动画比较流畅的案例可以分享一下。

**Comment by minwe** [comment]
Merge to #12.
