### ISSUE TITLE
Amaze UI Touch 开发者预览反馈

### ISSUE THREAD

**Issue by minwe** [amazeui/amazeui-touch#2]
Amaze UI Touch 目前出于开发者内部预览阶段，诸多细节还在调整完善。

对预览版有何见解请在此 issue 中参与讨论，**请勿再单独开 issue 讨论预览版问题**。

**Comment by rlog** [comment]
页面切换时中间有个较大的空隙

**Comment by rlog** [comment]
感觉有些AmazeUI里的组件并没集成进来，像dropdown，之后还会补充吗？

**Comment by LeoSunCN** [comment]
###  给没配置好环境的同学说一下环境配置问题
需要安装git\node.js\python2.7(不要安装3.x)\VS2015（或者VS2013）\WindowsSDK(一般安装VS的时候把Windows SDK勾选上就行了),并且配置相应的环境变量
如果执行gulp ks出现
'gulp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
那么请先执行npm i gulp -g
可以忽略警告，不可忽略错误ERR

**Comment by LeoSunCN** [comment]
![img_2372](https://cloud.githubusercontent.com/assets/4363307/10474025/888988ac-7264-11e5-8541-93a1d82ec7b6.PNG)
![img_2373](https://cloud.githubusercontent.com/assets/4363307/10474027/889ac838-7264-11e5-80ba-eccf57ac38ee.PNG)
![img_2374](https://cloud.githubusercontent.com/assets/4363307/10474026/88993414-7264-11e5-9e7f-a9d12d0da39d.PNG)
![img_2375](https://cloud.githubusercontent.com/assets/4363307/10474029/88c169f2-7264-11e5-8fa9-6e95fc3f2bb4.PNG)
![img_2376](https://cloud.githubusercontent.com/assets/4363307/10474030/88c2ec8c-7264-11e5-92a9-e75005568bb8.PNG)
![img_2377](https://cloud.githubusercontent.com/assets/4363307/10474028/88b14ca2-7264-11e5-9349-c02359837c60.PNG)
![img_2378](https://cloud.githubusercontent.com/assets/4363307/10474032/88cb70c8-7264-11e5-82d2-d67e12a6d619.PNG)
![img_2379](https://cloud.githubusercontent.com/assets/4363307/10474031/88cac81c-7264-11e5-9ea8-7d796e322ef0.PNG)


Modal 基本上都有问题，在PC Chrome上仿真时没有问题，但是在Iphone的Safari和Chrome上都有问题，弹出框弹出后，背景仍然可以滑动， Popup Modal错位

显示通知栏无效

**Comment by hogenwang** [comment]
小米4c 安卓5.1.1 下面，严重有问题，样式不兼容。而且整体效果不流畅

![qq 20151014144424](https://cloud.githubusercontent.com/assets/9367767/10476627/1edc90b6-7282-11e5-8ff0-01632470e9d8.jpg)

**Comment by minwe** [comment]
@hogenwang 列表箭头问题应该是 flexbox 的浏览器前缀没有加完整引起的，我们已经做了调整，回头再测试一下。

@all:

谢谢各位参与，提到问题已经整理到独立的 issue 中。Amaze UI Touch 进入小范围公测阶段，此 issue 关闭。

欢迎大家继续参与、反馈。
