### ISSUE TITLE
文档能不能详细一点哈

### ISSUE THREAD

**Issue by carr123** [amazeui/amazeui-touch#22]
amazeui-touch 的安装文档能不能详细点哈， 像amazeui那样详细。
amazeui.touch.min.css 文件都找不到哈。

**Comment by minwe** [comment]
如果你是用 npm 安装的那就是在 `node_modules/amazeui-touch/dist` 下面。

**Comment by jieyou** [comment]
css/scss文件只能全体引入，不能根据模块引入吗？

**Comment by minwe** [comment]
@jieyou 目前使用 SASS，CSS 和 JS 还是相对独立的，暂不能根据模块打包 CSS。以后考虑其他更完整的模块化方式。

**Comment by minwe** [comment]
@carr123 相关内容已经做补充。

**Comment by minwe** [comment]
@jieyou 从 `1.0.0-rc.1` 开始支持 CSS 按需打包了，具体参见文档：https://github.com/amazeui/amazeui-touch/tree/ff9accf7d3b403bc40052e27a3af0ed1e9ffc95b/docs/components/advanced
