### ISSUE TITLE
滚动不流畅

### ISSUE THREAD

**Issue by demon-cai** [amazeui/amazeui-touch#23]
在微信里面滚动很不流畅呀，体验不是很高

**Comment by yinzSE** [comment]
android webapp 性能就那样,
这和react 以及 ameze 没啥关系.

另外 react 里的 onScroll 事件挂钩组件状态的时候 请慎重使用, 严重影响性能

**Comment by caopeng945** [comment]
页面滚动的时候感觉不流畅，这个应该不是性能问题，我用的ios直接扫二维码访问的官网例子，滚动的时候还是很卡顿，以前用过web amazeui 没有这个问题，暂时决定弃用

**Comment by minwe** [comment]
iOS 滚动不流畅是因为滚动条在一个 div 上，没有设置  `-webkit-overflow-scrolling: touch`（该属性会影响 Modal 和 Notification 之类的组件工作）。

如果不使用 `Container` 组件，直接把滚动条放在 HTML 上，就不会有这个问题。

后续会考虑 Modal 等组件的实现方式，让容器能够应用  `-webkit-overflow-scrolling: touch`。
