### ISSUE TITLE
表单filed可能需要改进一下

### ISSUE THREAD

**Issue by YiWind** [amazeui/amazeui-touch#26]
```javascript
<Field labelBefore="验证码" placeholder="请输入验证码" btnAfter={<Button>获取验证码</Button>} />
```
这里如果把 labelBefore="验证码" 改成label="验证码"，则不会显示btnAfter的按钮了。
![upload](https://cloud.githubusercontent.com/assets/7425503/12445707/e3bcf6c6-bfa0-11e5-9186-3e7354bbc7f3.jpg)

**Comment by minwe** [comment]
这个没问题了吗？上周四开始没在。
