### ISSUE TITLE
不要直接在文件里调用 "Object.assign" 

### ISSUE THREAD

**Issue by jianguangyu** [amazeui/amazeui-touch#27]
ButtonGroup   Touchable  PopoverTrigger 这三个类直接调用了Object.assign。这会产生兼容性问题，请修改一下

**Comment by minwe** [comment]
谢谢提醒，印象中 babel 转换的时候会使用相关插件替换的，回头再确认一下。

**Comment by minwe** [comment]
Babel 转换后会自动替换成以下代码：

```javascript
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
```

参考：https://github.com/babel/babel/tree/development/packages/babel-plugin-transform-object-assign

**Comment by jianguangyu** [comment]
我不确定你有没有听懂我的意思。Babel转换后生成这个定义后，那么调用的地方也应该替换成_extends,但是这三个文件里依然用的是Object.assign，而不是_extends.
这应该只是举手之劳，你们改一下不就好了。

**Comment by minwe** [comment]
呃，确实有没有替换的，应该是插件有问题。
