### ISSUE TITLE
安卓系统下Button控件报错，不能使用

### ISSUE THREAD

**Issue by flyzb618** [amazeui/amazeui-touch#29]
我用了QQ、百度、360手机浏览器测试了http://t.amazeui.org/站点上button控件示例，发现打不开。

**Comment by minwe** [comment]
系统版本、以及浏览器的版本分别是多少？

**Comment by flyzb618** [comment]
我的安卓系统是5.1.1 ,  QQ的版本是6.4.1.2055，百度的是V6.4

我觉的应该跟手机版本和浏览器版本没什么关系，因为我让另外2个同事测试了也是如此，他们的手机型号和我不同，但bug现象是相同的

**Comment by minwe** [comment]
有可能是 #27 里提到的 `Object.assign` 的问题，你可以克隆最新的源代码本地跑一下试试。

**Comment by flyzb618** [comment]
按你说的测试了一下，确实可以了，拿什么时候能更新一下npm吗？

**Comment by minwe** [comment]
应该要等几天再看看其他问题才更新。

你可以尝试在你的项目中加上 https://github.com/babel/babel/tree/development/packages/babel-plugin-transform-object-assign 这个插件

**Comment by minwe** [comment]
Resolved via 49035679e1e3c55e043eeae02df1dd62be8c71c9.

**Comment by minwe** [comment]
@flyzb618 新版本已经更新。
