### ISSUE TITLE
关于tabbar

### ISSUE THREAD

**Issue by transtone** [amazeui/amazeui-touch#30]
kitchen-sink/app.js 中tabbar是一直存在的，在实际使用中tabbar肯定会有变化：有些页面不需要显示，badge内容变化。这种情况如何处理呢？

放在app.js 文件中，children页面可以更改父级元素内容吗？

这个是 react-router 的使用问题，不知道能不能在这里问。

**Comment by minwe** [comment]
React 虽然很热，但个人觉得还没有形成相对成熟的、完整的配套方案，在一些特殊的实际场景中无从下手，只有逐步摸索。

React 组件有着严格的层级关系，组件之间通讯有时会很麻烦，特别是没有没有上下级关系的组件之间：

- 有上下级关系的组件通讯可参考官方文档，主要是通过 `props` 传递和 `context` 
    - http://facebook.github.io/react/tips/communicate-between-components.html
    - http://facebook.github.io/react/docs/context.html
- 没有上下级关系的组件：可以通过全局的事件系统来通讯

当然我上面说的都是理论，对于你提到的问题我也没有实际处理经验，只能在后续的开发使用中进一步探索。

React Router 更新太快，还没来得及升级到 `2.0.0`。

你可以参看一下 React Router 的示例 https://github.com/reactjs/react-router/tree/master/examples ，看是否涉及相关问题。
