### ISSUE TITLE
Amaze UI Touch官网介绍中『开始使用』页面在移动端无法滚动浏览

### ISSUE THREAD

**Issue by yangzj1992** [amazeui/amazeui-touch#31]
MX5 PRO打开amaze ui touch[开始使用](http://t.amazeui.org/#/docs?_k=e214ps)页面在微信和UC上都有无法滑动的问题。

**Comment by minwe** [comment]
UC 和微信的版本各是多少？

**Comment by yangzj1992** [comment]
weixin:6.3.13
UC:10.9.5.729
