### ISSUE TITLE
React 版和 Touch 的区别以及 Touch 布局使用问题

### ISSUE THREAD

**Issue by guotingchaopr** [amazeui/amazeui-touch#32]
## 问题描述
React  和 Touch的区别在哪 为什么  Touch底部菜单是 Tabbar React 又是Navbar 而且 Touch的布局没有太详细的说明 我一直不知道怎么才能把Touch版本的Tabbar定位到底部而不影响其他的元素

**Comment by minwe** [comment]
React 版的全称是 Amaze UI Web React，也就是原来的 Amaze UI Web（jQuery）用 React 实现了。

Touch 是全新的完全基于 React 、只面向移动端开发的版本，比原来的要轻一些。

二者在组件命名上并不完全一致。

Touch 版使用 flexbox 实现的布局，你熟悉一下 flexbox 就能搞定你想要的布局效果了。

**Comment by minwe** [comment]
近期会整理一个简要的 Amaze UI Web 和 Amaze UI Touch 对比表格，有其他关于二者的疑惑可以继续提出来。谢谢！

**Comment by lzkwin** [comment]
QQ浏览器里的布局有点问题？标题栏不居中

**Comment by minwe** [comment]
@lzkwin 安卓？flexbox 在一些国产浏览器中兼容性问题比较多。

**Comment by zhangda47** [comment]
微信浏览器错版

**Comment by minwe** [comment]
@lzkwin @zhangda47 参见 #12。
