### ISSUE TITLE
一些bug及建议

### ISSUE THREAD

**Issue by wzsxyz** [amazeui/amazeui-touch#33]
bug：
prompt的modal边输入边触发onSelect，该组件基本无法使用
普通modal包含表单时关闭再打开rc-form验证模块就异常了（open前强制重新渲染一下可解决）
action的modal的取消按钮会提交表单，该组件也是残废

建议：
modal（主要是prompt）要提供beforclose事件，能阻止关闭，不然很难用
组件应提供更灵活的定制，比如tabs的body，不配置内容也会占位，并且无法去除，有时根本不想要

总的来说有被坑的感觉，看着组件很全，但用起来都是坑

**Comment by minwe** [comment]
谢谢反馈！

`onSelect ` 这个接口与 React 事件接口命名冲突，已经重命名为 `onAction`。

其他细节会逐步完善。React 相对较新，其开发模式还有待进一步积累改进。

**Comment by minwe** [comment]
ed81459aba1180aaf36ffa08080231919379cf0a 中已经增加对 `prompt` 点击确定时是否关闭的处理逻辑。

对于更复杂的表单，可以自己组织 Modal 的内容，包括按钮（不使用 `prompt` 模式），以编写更多控制逻辑。
