### ISSUE TITLE
ButtonGroup和tabbar组件在微信端显示异常

### ISSUE THREAD

**Issue by flyzb618** [amazeui/amazeui-touch#34]
ButtonGroup和tabbar组件在微信端无法正常显示

**Comment by minwe** [comment]
- **设备及型号：**（手机、平板等移动设备时填写此项，如 `iPhone 6s Plus`）
- **操作系统及版本：**（在系统设置关于里面可以查看）
- **浏览器及版本：**（一般在浏览器「帮助」或者「关于」里面）
- **问题截图/录屏：**

**Comment by kukulu00** [comment]
这个问题我知道，用master版本编译一下就好了。
不过，什么时候可以更新一下node上的版本
现在的[tag]beta2还不到修复这两个组件的版本

**Comment by minwe** [comment]
如果是 @kukulu00 说的问题的话，那在 3d6bbdc 中已经解决。
