### ISSUE TITLE
NavBar在小米手机的微信中显示错误

### ISSUE THREAD

**Issue by kukulu00** [amazeui/amazeui-touch#38]
更新最新的master后看sk中的例子nav明显错误

小米4 微信内置的那啥核浏览器

**Comment by minwe** [comment]
请提供 MIUI 版本、微信版本信息。

**Comment by kukulu00** [comment]
型号 MI 4LTE-CMCC
Android 4.4.4 KTU84P
微信6.3.15
MIUI 7.1.4.0(KXDCNCK)

**Comment by minwe** [comment]
合并至 #12 处理。
