### ISSUE TITLE
如何将offCanvas用在Navbar上面？

### ISSUE THREAD

**Issue by YuxinChou** [amazeui/amazeui-touch#40]
## 如何将offCanvas用在Navbar上面？

官网给出的例子，是2个单独使用时的举例。

对于如何在Navbar的左边或右边放置一个按钮，实现offCanvas的功能，试了几次都未成功。

求大神指导一下，谢谢

**Comment by minwe** [comment]
现在二者结合一起使用有点问题，需要做一些调整。

临时的办法是通过 CSS 定位把按钮放到 NavBar 上。
