### ISSUE TITLE
示例程序在 webpack 打包过程中报错

### ISSUE THREAD

**Issue by glassysky** [amazeui/amazeui-touch#43]
按照这个示例
[http://t.amazeui.org/#/docs?_k=ren5hu](http://t.amazeui.org/#/docs?_k=ren5hu)
在用 webpack 打包 js 文件时，出现错误
![image](https://cloud.githubusercontent.com/assets/11582268/15114353/240b82c4-162c-11e6-9def-06082fb9c982.png)

JS 文件如下
![image](https://cloud.githubusercontent.com/assets/11582268/15114378/415f9eb4-162c-11e6-93fd-3d8e870328f8.png)

webpack loader 配置如下
![image](https://cloud.githubusercontent.com/assets/11582268/15114392/5a4ecad0-162c-11e6-9e1f-804ce275daec.png)

**Comment by minwe** [comment]
`presets` 里加上 `react`：

http://babeljs.io/docs/plugins/preset-react/
