### ISSUE TITLE
[bug]npm上的1.0.0-beta.1版本是不是没有build,和源码对不上

### ISSUE THREAD

**Issue by garylgh** [amazeui/amazeui-touch#46]
## 问题描述

npm上安装最新的版本（v1.0.0-beta.1），发现dist与源码不一致，是不是没有build就发布到npm了？

## 产生环境

- **设备及型号：iPhone 6s Plus
- **操作系统及版本：Mac EL Capitan
- **浏览器及版本：chrome 50.0
- **问题截图：

下面是NavBar的renderNavItem方法的三张截图。
第一张为React源码图
第二张为npm下dist里babel编译后的截图
第三张为本地build后dist里babel编译后的截图
![navbar-source](https://cloud.githubusercontent.com/assets/1640139/15421545/764dd35c-1ea6-11e6-9d05-5ad4ecb7c67b.png)
![navbar-babel-npm](https://cloud.githubusercontent.com/assets/1640139/15421553/87e4b108-1ea6-11e6-83fa-bf9d9d7a1d89.png)
![navbar-babel-local](https://cloud.githubusercontent.com/assets/1640139/15421560/9390fa7a-1ea6-11e6-9d26-a2a70ce17615.png)

**Comment by minwe** [comment]
你看的是最新的源代码，不是 `v1.0.0-beta.1` 那个 tag 下面的。

https://github.com/amazeui/amazeui-touch/tree/aadf2a2dbacf6936d48b2c34a1f4152d32e65349 才是 `v1.0.0-beta.1` 对应的源码。

**Comment by garylgh** [comment]
恩，我错了。npm装的是v1.0.0-beta.1，我clone的是master，没仔细想这当中会有提交。
beta.1的bug，用master build了以后就没了，问题解决了，谢谢。
