### ISSUE TITLE
TabBar  集合 react-router 使用问题

### ISSUE THREAD

**Issue by coderjiang2013** [amazeui/amazeui-touch#53]
## 问题描述

使用 TabBar 组件 结合 react-router 时，children 组件 props.selected 始终是false。

入口写法参考官方demo
https://github.com/amazeui/amt-starter-kit/blob/master/app/js/app.js

请问 TabBar 选中后 avtive class 的处理是哪里处理的？  需要在 TabBar 的 onAction 中处理么？ 

有没有官网组件demo的代码可以学习一下

**Comment by minwe** [comment]
`selected` 为 `true` 的时候自动添加 `active` className。

如何判断当前 route 是否激活可以翻一下 React Router 文档。

**Comment by coderjiang2013** [comment]
翻了些资料，应该是Router 用 Link 的时候，会自动增加 Avtive class，
`<TabBar.Item
                        component={Link}
                        icon="person"
                        title="注册"
                        selected={params.page === 'register'}
                        to="/register"
                    />`

` <Route path="/register" getComponent={ (nextState, callback) =>{
                require.ensure( [ ], (require) => {
                    callback(null, require("./pages/RegisterForm").default)
                })
            } }/>`

新人求高手指点一下

**Comment by minwe** [comment]
根据 router 判断当前链接是否激活，然后把这个 boolean 值传给 `<TabBar.Item>` 的 `selected` 属性。

具体实现参见 https://github.com/amazeui/amt-starter-kit/blob/465d324ff466a7fd8608bea78afb82fb6e05b966/app/js/app.js#L52-L53。

**Comment by minwe** [comment]
更简单的方式就是设置 `activeClassName`，让 `<Link>` 自己处理：

```javascript
<TabBar.Item
  component={Link}
  icon="person"
  title="注册"
  to="/register"
  activeClassName="active"
/>
```

https://github.com/reactjs/react-router/blob/master/docs/API.md#activeclassname

> `activeClassName`
>
> The className a `<Link>` receives when its route is active. **No active class by default.**

**Comment by coderjiang2013** [comment]
selected={router.isActive('/register', true)} 这种方式好一点

activeClassName="active" 用在 to="/" 貌似会失效

amaze touch 想玩转，技术栈还是挺深的 :dancers:
