### ISSUE TITLE
设置container组件的scroll属性为true后，slider组件中的图片会丢失一部分

### ISSUE THREAD

**Issue by littlepoolshark** [amazeui/amazeui-touch#54]
> 欢迎你为 Amaze UI 添砖加瓦。
>
> - 如果你想反馈 bug 或者使用问题，请**务必**按照以下格式提交，以便问题定位和解决，节省来回问答的时间；
> - 如果你不熟悉 Markdown 语法，请先阅读 [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)；
> - 如果你不知道如何上传文件，请参考 [File attachments on issues and pull requests](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)，或者留意一下输入框底部的小字 `Attach files by dragging & dropping, selecting them, or pasting from the clipboard.`，点击 **selecting them** 也可以上传；
> - 最后，请在提交 issue 之前删除提示性的文字，包括本行及以上部分，以及下面括号中的内容。

## 问题描述

在pc端谷歌浏览器里面，手机模拟iphone6，设置container组件的scroll属性为true后，slider组件中的图片会丢失一部分。我将container-scroll样式类的overflow-x和overflow-y的值设置为hidden之后（也就相当于禁用div的滚动），这个时候，图片中缺失的部分就会出现。

## 产生环境

- **设备及型号：**（手机、平板等移动设备时填写此项，如 `iPhone 6s Plus`）
- **操作系统及版本：** window 7 64位
- **浏览器及版本：** 谷歌浏览器 52.0.2723.3 m
- **演示地址：**（请尽量提供可在线查看的演示地址）
- **问题截图/录屏：**

  （截图和录屏有助于我们更直观的理解你想表达的问题。如果需要，你可以使用 [LICEcap](http://www.cockos.com/licecap/
![dp d62qce_ iez _sefjegt](https://cloud.githubusercontent.com/assets/7507174/15988842/e98b654e-3091-11e6-8242-00abc925c41e.png)
) 录制 GIF 动画）
![514zql jte 493 6r 74 nt](https://cloud.githubusercontent.com/assets/7507174/15988833/80c4a4b2-3091-11e6-99b9-f9181c3e7d95.png)

## 复现步奏

1.
2.
...

**Comment by minwe** [comment]
Chrome 51 无法复现这个问题，你检查一下图片比例是否一致，从截图看，Slider 的容器是比图片高的。

**Comment by minwe** [comment]
长时间无反馈，暂时关闭。
