### ISSUE TITLE
Icon 可以动态设置name属性么？

### ISSUE THREAD

**Issue by coderjiang2013** [amazeui/amazeui-touch#55]
## 问题描述

有一个List， 每个记录有几个 Icon 作为收藏与否的标记，点击后变为收藏，
使用 refObj.props.name = 'star-filled';

报错Cannot assign to read only property 'name' of object

有什么办法么？

...

**Comment by minwe** [comment]
React 不是这么用的，需要改变的属性和状态关联，修改状态，而不是直接修改属性。

```javascript
const MyComponent = React.createClass({
  getInitialState() {
    return {
      stared: false,
    }
  },
  
  handleClick() {
    this.setState({
      stared: !this.state.stared
    })
  },
  
  render() {
    return (
      <div>
        <Icon name={this.state.stared ? 'star-filled' : 'star'} />
        <button onClick={this.handleClick}>测试</button>
      </div>
    );
  }
});
```

**Comment by coderjiang2013** [comment]
代码结构如下， Card 的 footer 里有一个 Icon， 没办法在这个组件里声明 N 个 state 绑定状态， 有什么好办法么？大神，　　难道要把Card再封装一次？

                    {this.state.messageContent.map((message, i) => {
                        return (
                            <Card
                                key={i}
                                title={message.name}
                                footer={this.getMessageFooter(message)}
                            >
                                {message.desc}
                            </Card>
                        );
                    })}

**Comment by coderjiang2013** [comment]
getMessageFooter(message)
        {
            if (message.withReply) {
                return (
                    <Card.Child role="footer">
                        <Icon ref="fav"
                              name={message.isFavorite ? 'star-filled' : 'star'}
                              ref={'message_' + message.id}
                              id={message.id}
                              onClick={this.favorite}/>
                        <a href="#/">Comment</a>
                    </Card.Child>
                );
            } else {
                return (
                    <Card.Child role="footer">
                        <Icon ref="fav"
                              name={message.isFavorite ? 'star-filled' : 'star'}
                              ref={'message_' + message.id}
                              id={message.id}
                              onClick={this.favorite}/>
                    </Card.Child>
                );
            }
        }

**Comment by minwe** [comment]
你可以把 star 的消息 ID 存在数组里，渲染的时候看看数组里有没有这调消息的 ID。

```javascript
const MyComponent = React.createClass({
  getInitialState() {
    return {
      favorites: [],
    }
  },

  handleClick() {
    this.setState({
      stared: !this.state.stared
    })
  },

  renderMessageFooter(message) {
    return (
       <Card.Child role="footer">
                    <Icon ref="fav"
                          name={this.satet.favorites.indexOf(message.id) > -1 ? 'star-filled' : 'star'}
                          ref={'message_' + message.id}
                          id={message.id}
                          onClick={this.favorite}/>
                    <a href="#/">Comment</a>
                </Card.Child>
    );
  }
});
```

**Comment by coderjiang2013** [comment]
是个好办法，明白
