### ISSUE TITLE
请问用 touch 开发，有核是的ajax插件配合么？

### ISSUE THREAD

**Issue by coderjiang2013** [amazeui/amazeui-touch#57]
请问大神，使用 touch 开发的时候，有ajax的插件配合么？ 不想用jQuery，太大了

**Comment by coderjiang2013** [comment]
目前只有ajax用了jQuery，貌似没有必要引入一个100多K的库

**Comment by minwe** [comment]
你可以：

- 直接用原生的 XMLHttpRequest
- 或者其他比较轻量的 Ajax 封装
- 或者 fetch https://github.com/matthew-andrews/isomorphic-fetch
