### ISSUE TITLE
touch 性能问题

### ISSUE THREAD

**Issue by coderjiang2013** [amazeui/amazeui-touch#58]
touch H5页面，在微信里来回切换页面很不流畅，不知道是我使用问题，还是需要什么优化呢？

    render() {
        const {
            location,
            children
        } = this.props;

        return (
            <Container direction="column" id="sk-container">
                <div className="views">
                    <div className="view" id="app-index" id="app-index">
                        <Container
                            transition={this.state.transition}
                        >
                            {React.cloneElement(children, {key: location.key})}
                        </Container>
                    </div>
                </div>
                {this.getFooter()}
            </Container>
        );
    }

**Comment by minwe** [comment]
性能对于 Android 某些机型和浏览器而言就是硬伤，不可能做到所有机型都一致的体验，如果特别卡的话，可以考虑在这些场景中取消动画。

**Comment by coderjiang2013** [comment]
Container 组件里，貌似没有参数可以关闭转场动画的参数

**Comment by minwe** [comment]
去掉  `transition` 属性就没有动画了。
