### ISSUE TITLE
利用cordova 打包后Modal 和Notification 组件都报错document.body is null，紧急！！！

### ISSUE THREAD

**Issue by fangjj** [amazeui/amazeui-touch#59]
> 欢迎你为 Amaze UI 添砖加瓦。
>
> - 如果你想反馈 bug 或者使用问题，请**务必**按照以下格式提交，以便问题定位和解决，节省来回问答的时间；
> - 如果你不熟悉 Markdown 语法，请先阅读 [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)；
> - 如果你不知道如何上传文件，请参考 [File attachments on issues and pull requests](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)，或者留意一下输入框底部的小字 `Attach files by dragging & dropping, selecting them, or pasting from the clipboard.`，点击 **selecting them** 也可以上传；
> - 最后，请在提交 issue 之前删除提示性的文字，包括本行及以上部分，以及下面括号中的内容。

## 问题描述

利用cordova 打包后Modal 和Notification 组件都报错 cannot read property 'appendChild' of null,我看源代码有
const bodyElement = canUseDOM ? document.body : {appendChild: () => {}};然后我打印document.body为null。我使用官方demo，导致打不开NotificationExapmle和ModelExample页面。
## 产生环境

- **设备及型号：** android 4.2.2 桌酷
- **操作系统及版本：**（在系统设置关于里面可以查看）
- **浏览器及版本：**（一般在浏览器「帮助」或者「关于」里面）
- **演示地址：**（请尽量提供可在线查看的演示地址）
- **问题截图/录屏：**
-** cordova版本：** 
-** cordova-plugin-crosswalk-webview：** 1.6.0

  （截图和录屏有助于我们更直观的理解你想表达的问题。如果需要，你可以使用 [LICEcap](http://www.cockos.com/licecap/) 录制 GIF 动画）

## 复现步奏

1.
2.
...

**Comment by fangjj** [comment]
刚才在ModalPortal.js中document.body换成，var body = {appendChild: () => {}};不报错，然后就可以进页面，但是不能弹出modal，更加说明，document.body为null，怎么解决。着急。

**Comment by minwe** [comment]
Cordova 里没有 `document.body`?

没用过 Cordova，具体细节还得进一步了解。

**Comment by fangjj** [comment]
我想可能跟cordova有关系，但是项目里也做了特殊处理，说明设计人是知道的。https://github.com/amazeui/amazeui-touch/search?utf8=%E2%9C%93&q=const+bodyElement+%3D+canUseDOM+%3F+document.body+%3A+%7BappendChild%3A+%28%29+%3D%3E+%7B%7D%7D%3B

**Comment by fangjj** [comment]
后面又被注释了，不知道是修复还是怎么的。

**Comment by minwe** [comment]
临时的解决方案：

你在你写的页面 body 里写一个 `<div id="__portal-container"></div>`，

然后把 body 的指向改为这个 `div`：

```javascript
const body = document.getElementById('__portal-container');
```

**Comment by fangjj** [comment]
好的。谢谢你。

**Comment by minwe** [comment]
应该是你的 JS 执行时机有问题：

```javascript
document.addEventListener('deviceready', onDeviceReady, false); 
```

`deviceready` 之后再渲染你的应用。

**Comment by fangjj** [comment]
document.addEventListener('deviceready', onDeviceReady, false); 
document.addEventListener('DOMContentLoaded', function() {
     ReactDOM.render(routes, document.getElementById('sk-root'));
  });
你的意思是要这样写？

**Comment by minwe** [comment]
```js
document.addEventListener('deviceready', function() {
   ReactDOM.render(routes, document.getElementById('sk-root'));
});
```

应该是这样。

**Comment by fangjj** [comment]
明白了，就来测试。

**Comment by minwe** [comment]
https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.deviceready.html

按照官方文档也可能是：

```javascript
document.addEventListener('DOMContentLoaded', function() {
  document.addEventListener('deviceready', function() {
     ReactDOM.render(routes, document.getElementById('sk-root'));
  });
});
```

具体你试试。

**Comment by fangjj** [comment]
好的。我处理好了，给你回复。

**Comment by fangjj** [comment]
弄好了。谢谢你。

**Comment by minwe** [comment]
你最终是哪个方式解决的？可以明确一下给其它人参考。

**Comment by fangjj** [comment]
正向你所说一样，我在应用开始就import amazeui-touch，会导致document.body为null。document.addEventListener('DOMContentLoaded', function() {
if(isCordova){
document.addEventListener('deviceready', function() {
     ReactDOM.render(routes, document.getElementById('sk-root'));
  });
}else{
ReactDOM.render(routes, document.getElementById('sk-root'));
}
  
});
