### ISSUE TITLE
Icon 组件问题

### ISSUE THREAD

**Issue by stevenlvcrow** [amazeui/amazeui-touch#60]
Icon组件设置href时 在编译为<a>标签时 href里的内容被置为空。这是bug么？
`   <Icon name='home' href="/head"></Icon>
           <div className="sk-icon-name text-truncate">
                    管理
           </div>
`
这是代码。然后被编译成了这样。
`<a class="icon icon-home"></a>`

还是我使用的方式有问题？

**Comment by stevenlvcrow** [comment]
另外 在使用grid组件的时候。没有网格线的属性么。采用九宫格布局时会用到这个

**Comment by minwe** [comment]
是有问题，图标的 `href` 属性没有传进去。

**Comment by minwe** [comment]
Fixed via d85beb8c7a3086841f4295b40e95fb00c153a284.
