### ISSUE TITLE
如何js控制LInk跳转

### ISSUE THREAD

**Issue by fangjj** [amazeui/amazeui-touch#63]
> 欢迎你为 Amaze UI 添砖加瓦。
>
<TabBar.Item
  < TabBar.Item
  component={Link}
  title="退出"
  to="/"
  onClick={this.onLogout}
  />

## 问题描述

我想在onLogou方法中，return true，即可跳转路由 "/"，return false，提示失败，不进行跳转。不知道怎么实现。

**Comment by minwe** [comment]
参考 React Router 文档和例子：

- https://github.com/reactjs/react-router/tree/master/examples/auth-flow
- https://github.com/reactjs/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md
- https://github.com/reactjs/react-router/blob/master/docs/API.md#contextrouter

**Comment by fangjj** [comment]
谢谢你的回复。新手多多关照。

**Comment by minwe** [comment]
使用时会遇到的问题一般文档和例子中都会提及，多翻翻就熟了。

**Comment by fangjj** [comment]
是的。参考kitchen，然后看看底部源代码，自己写小项目，目前感觉还不错，有什么问题，我就提issue啊，不嫌弃我把。
