### ISSUE TITLE
如何为整个页面(View)跳转添加动画

### ISSUE THREAD

**Issue by fangjj** [amazeui/amazeui-touch#64]
> 欢迎你为 Amaze UI 添砖加瓦。

## 问题描述

![20160620004820](https://cloud.githubusercontent.com/assets/15318800/16178646/be541aa2-3680-11e6-8d38-89d9cf53aa99.png)

**Comment by minwe** [comment]
参考：

- https://github.com/reactjs/react-router/tree/master/examples/animations
- https://facebook.github.io/react/docs/animation.html

**Comment by fangjj** [comment]
谢谢你给我找的资源，这个问题，我看到kitchendemo，是Container里面切换有动画，我在想能不能View外面再套一层Container就可以有动画了。

**Comment by minwe** [comment]
是的，kitchen-sink 里也是这么实现的，搞清 Router 的结构以后就很直观了。

**Comment by fangjj** [comment]
好的。我就来试试。
