### ISSUE TITLE
考虑为Card组件，新增一个属性noMargin

### ISSUE THREAD

**Issue by fangjj** [amazeui/amazeui-touch#65]
## 问题描述
喜欢Card的样式，但是它有margin，所有，只有自己传人className修改样式。可以考虑新增noMargin和其他组件noPadded一样。
![card](https://cloud.githubusercontent.com/assets/15318800/16182135/3eb9b1d0-36d5-11e6-90a7-6d505a5cf1d7.png)

**Comment by minwe** [comment]
有个 `margin` 的工具类名：http://t.amazeui.org/#/docs/utility

```
<Card className="margin-0">
  ...
</Card>
```

**Comment by fangjj** [comment]
谢谢啊。有了你的帮忙。
