### ISSUE TITLE
考虑提供flex兼容写法的工具css类

### ISSUE THREAD

**Issue by fangjj** [amazeui/amazeui-touch#67]
## 问题描述
有时候，需要自己写组件，希望能用amazeui-touch中flex的样式，有工具类最好。

**Comment by minwe** [comment]
我们都是按照标准写，然后用 Autoprefixer 自定添加兼容前缀的。

如果需要可以从网上找相关内容，如：

- https://github.com/mastastealth/sass-flex-mixin/blob/master/_flex.scss
