### ISSUE TITLE
List.Item 使用过程中一些建议

### ISSUE THREAD

**Issue by fangjj** [amazeui/amazeui-touch#68]
###问题描述
使用List.Item中很多时候，需求是点击它，有点击阴影效果，然后自己写点击事件。而官方demo中，只有加有linkComponent、href才有这样点击效果，但是加上这些后，就无法执行自己的点击事件，因为这时候，路由有变化。想听听你的意见。

**Comment by minwe** [comment]
- 增加 `href` 属性后，在 `onClick` 处理函数里 `e.preventDefault();` 可以阻止默认的链接跳转；
- 通过定义 `.item:active` 样式也可以。
