### ISSUE TITLE
Cannot read property 'addons' of undefined

### ISSUE THREAD

**Issue by mingtian110** [amazeui/amazeui-touch#74]
## 问题描述
页面渲染时报未捕获的错误,但是页面依旧可以渲染
报错内容是:
Uncaught TypeError: Cannot read property 'addons' of undefined：也就是
root["React"]返回undefined.
![image](https://cloud.githubusercontent.com/assets/11565694/16475737/8853b828-3eb3-11e6-91b7-668636c49e03.png)

错误产生于	@	amazeui.touch.js:13行:
该行内容为:
root["AMUITouch"] = factory(root["React"], root["React"]["addons"]["CSSTransitionGroup"], root["ReactDOM"]);
![image](https://cloud.githubusercontent.com/assets/11565694/16475749/a0f23f8a-3eb3-11e6-9f6c-eff7b50d5e64.png)
## 产生环境
谷歌浏览器:51.0.2704.103 m
"amazeui-touch"的版本: "1.0.0-beta.4",
模拟的是:
![image](https://cloud.githubusercontent.com/assets/11565694/16475583/4c11cd56-3eb2-11e6-8089-221f369af292.png)
操作系统:win7

**Comment by minwe** [comment]
> Amaze UI Touch 使用了 React CSS Transition Group add-on，引入 React 时需使用包含 add-ons 的版本 `react-with-addons.min.js`

**Comment by mingtian110** [comment]
好了,谢谢
