### ISSUE TITLE
Bug:amazeui-touch的Modal报错

### ISSUE THREAD

**Issue by kylixfans** [amazeui/amazeui-touch#75]
**问题描述**

问题所在地址：
http://ask.amazeui.org/?/question/912

**产生环境**

- 设备：pc
- 操作系统及版本：win10
- 浏览器及版本：chrome
- 演示地址：

1. 运行kitchen-sink的代码
2. 点Modal，chrome报错
3. 刷新页面能出Modal演示页面，便点按钮，继续报错，没有Modal窗口弹出

 
**UA:** 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0 Waterfox/47.0
```

**Comment by minwe** [comment]
`document.body` 为 `null`，可能是脚本执行的时候还访问不到 `document.body`，把脚本上 `<body>` 结束之前。

按理 http://t.amazeui.org/kitchen-sink/#/modal?_k=xage70 这个页面是不会出错的，至少我没遇到过。

**Comment by fangjj** [comment]
刚刚逛官网发现modal，确实有错。你们还没有发现吗！！！另外，我发现modal页面，点击浏览器的后退，到历史前一个页面，modal才关闭，能不让先关闭modal，后后退到新页面。

**Comment by minwe** [comment]
@kylixfans 你说的问题我这无法重现，在 Win10 + Chrome 上也无法重现。如果必要的话，只能远程看看你那边什么情况 https://www.teamviewer.com/zhCN/ 。

**Comment by fangjj** [comment]
现在确实没有复现了。

**Comment by minwe** [comment]
具体原因未知，使用 Webpack 打包的版本无此问题。

如果感兴趣的话可以再试试使用 Browserify 的最新版本。

https://github.com/amazeui/amt-starter-kit/archive/browserify.zip
