### ISSUE TITLE
icon显示异常

### ISSUE THREAD

**Issue by mingtian110** [amazeui/amazeui-touch#77]
问题描述:

在使用 导航条组件(navbar)时,leftnav指定的icon为left-nav,到页面实际显示为"㭎",如下:
![image](https://cloud.githubusercontent.com/assets/11565694/16553532/c0c8f61e-41fb-11e6-8241-14e650ed0152.png)

代码为:
![image](https://cloud.githubusercontent.com/assets/11565694/16553565/e6ce3d42-41fb-11e6-96ab-781b926a1e42.png)

![image](https://cloud.githubusercontent.com/assets/11565694/16553555/d88a301a-41fb-11e6-9f18-42a7b3d12346.png)
页面编码为:
![image](https://cloud.githubusercontent.com/assets/11565694/16553725/d69c4f1c-41fc-11e6-876c-917bfc119e8f.png)
将页面编码更改为gbk或者自动检测,显示依然如此

## 产生环境

谷歌浏览器:51.0.2704.103 m
"amazeui-touch"的版本: "1.0.0-beta.4",
模拟的是:
![qq 20160704152550](https://cloud.githubusercontent.com/assets/11565694/16553502/a101ad6c-41fb-11e6-93be-151dfc76e854.png)
操作系统:win7

**Comment by minwe** [comment]
你用 Webpack 的话把安装 `url-loader` 然后添加以下配置：

https://github.com/amazeui/amazeui-touch/blob/99fc5e0efedcc4364fba4af500c1efa19143427e/webpack.docs.babel.js#L99-L110
