### ISSUE TITLE
大概如何实现以下的List界面？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#84]
List怎么能实现类似以下的界面？似乎ListItem不能有过多的customize？

例如：
![image](https://cloud.githubusercontent.com/assets/12795428/16809880/6fec5c76-4954-11e6-866a-508b6bc90910.png)

![image](https://cloud.githubusercontent.com/assets/12795428/16809819/434a3c2e-4954-11e6-944d-f9e97c7c63b8.png)

**Comment by minwe** [comment]
第一个根 Amaze UI Touch 提供的样式很接近，微调一下即可。

第二个自己去写样式吧。
