### ISSUE TITLE
能配合其他React插件来实现List的上拉刷新，下拉加载吗？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#85]
这是个很重要的功能，谢谢！

**Comment by minwe** [comment]
原来怎么实现就怎么实现，就是多了一层 React 而已，比如可以继续使用 iScroll，不过是在 React 组件装载完成以后去初始化。

- https://github.com/bryaneaton13/react-pull-to-refresh
- http://daily-javascript.com/articles/react-pull-to-refresh/
