### ISSUE TITLE
List太长会影响performance吗？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#86]
谢谢！

**Comment by minwe** [comment]
会。

具体优化可以参考
- http://stackoverflow.com/questions/30976722/react-performance-rendering-big-list-with-purerendermixin
- https://github.com/jwarning/react-scrollable-list
- https://facebook.github.io/react/docs/advanced-performance.html
- http://benchling.engineering/performance-engineering-with-react/
- https://github.com/seatgeek/react-infinite
- http://chairnerd.seatgeek.com/react-infinite-a-browser-ready-efficient-scrolling-container-based-on-uitableview/

**Comment by kdenz** [comment]
好的谢谢！我会弄弄看。这个框架确实是不错的样子~
