### ISSUE TITLE
为什么List.Item里面的title, subtitle, after, desc 用<div>就会有红色warning?

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#87]
因为想Customize，所以只是Text的话肯定不够用。
效果是有的，但是红色的warning一直弹啊~ 为什么会这样？谢谢！
![image](https://cloud.githubusercontent.com/assets/12795428/16829272/b3437f52-49c9-11e6-822e-256e36c13ac1.png)
![image](https://cloud.githubusercontent.com/assets/12795428/16829282/bddaca42-49c9-11e6-8f87-1960750fda70.png)
![image](https://cloud.githubusercontent.com/assets/12795428/16829300/cc8004ae-49c9-11e6-8c58-5cec8f8b9968.png)

**Comment by minwe** [comment]
https://facebook.github.io/react/warnings/unknown-prop.html

不影响使用，可以先忽略，后续我们会处理。

**Comment by minwe** [comment]
如果你用的是旧版本的话升级到 `1.0.0-rc.2`。

**Comment by kdenz** [comment]
@minwe 好的 谢谢！因为我很可能会用于production
