### ISSUE TITLE
Bug? <card.child cover="xxx"> xxx 的后面一定要有.jpg或.png等，相片才会显示？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#90]
例如我用
![image](https://cloud.githubusercontent.com/assets/12795428/16840610/343214fa-4a08-11e6-84ed-0ec4ad4a06fa.png)
![image](https://cloud.githubusercontent.com/assets/12795428/16840627/4e715f9c-4a08-11e6-995a-fb32aa42326d.png)

wrap了，还是显示不到图片，只能把url直接放在cover里才可显示

![image](https://cloud.githubusercontent.com/assets/12795428/16840717/be1029a0-4a08-11e6-9c80-951a6b45924c.png)

而且最好是有.jpg 或.png等的链接，才会比较有可能成功

这样的话，要css微调card cover 图片会变得不方便？

**Comment by minwe** [comment]
请看文档 http://t.amazeui.org/#/docs/card?_k=2yeleb，`cover` 只接受字符串即图片 URL 作为值。

`cover` 用作 `Card.Child` 的背景图片，你需要控制的话定义样式然后把类名传给 `Card.Child` 就行。

我觉得用一个库之前，可以先把文档及示例大概浏览的一遍，可能的话再看一下源码了解内部的实现方式。
