### ISSUE TITLE
popover 设不了placement？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#91]
![image](https://cloud.githubusercontent.com/assets/12795428/16841885/d40b5518-4a0d-11e6-982a-7f3f05f2a525.png)
无论是把placement="bottom" 放在PopoverTrigger 还是Popover里，都改变不了Popover方向
"" 和 '' 也没有区别

**Comment by minwe** [comment]
Popover 位置 **目前的实现是根据 `<PopoverTrigger>` 在窗口中的位置自动计算，暂不支持自定义。
