### ISSUE TITLE
Bug? <img>不能用于离线的 .svg，只能用于网上的 .svg

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#92]
同一个svg，下载并import了之后就不能用了，只能refer to 原本的html address

离线的svg会这样
Cannot GET /i/map-7.svg

**Comment by minwe** [comment]
检查一下你的路径对不对吧， `/i/map-7.svg`，看看控制台里报什么错。

**Comment by kdenz** [comment]
路径是对的，有没在entry.js import 我也试过了，没差别
![image](https://cloud.githubusercontent.com/assets/12795428/16987378/6edae2d4-4ebe-11e6-80bb-abd9d55d2245.png)
测试过起码 .jpg 和 .png 都没问题

运行就会这样报错
![image](https://cloud.githubusercontent.com/assets/12795428/16987401/a1122d16-4ebe-11e6-9ae8-959a4e9fce88.png)

**Comment by minwe** [comment]
**404 错误**，指定路径找不到相应文件。硬盘上文件存在跟 HTTP 服务器能不能访问到是两个概念。

**Comment by kdenz** [comment]
@minwe 噢噢~ 但是可以访问到硬盘上面的png, jpg 等？

**Comment by minwe** [comment]
svg 也是可以的，报 404 的话一般是你 HTTP 服务根目录里找不到这个文件。

具体需要自己去查证处理，这问题跟 Amaze UI Touch 没有关系。

**Comment by kdenz** [comment]
只有这样才行，我看是Amaze UI touch starter kit 的问题吧~
![image](https://cloud.githubusercontent.com/assets/12795428/17097745/b91e442c-5291-11e6-9456-6d50fdd68980.png)
![image](https://cloud.githubusercontent.com/assets/12795428/17097753/c2710528-5291-11e6-8901-d9ecaae8f452.png)

**Comment by minwe** [comment]
1. 直接写在 `src` 里的图片 Webpack 是不会帮你拷过去的，需要 `import` 进去。
2. Amaze UI touch Starter Kit 里的配置只涉及到里面用的资源， 使用了 `svg` 需要自行增加相关 loader  配置处理。
