### ISSUE TITLE
如何设置backNav的动画？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#93]
就是从一个页面跳到另一个页面，然后按返回的时候，怎么样设置这里的动画？谢谢！

**Comment by minwe** [comment]
参考：

- https://github.com/amazeui/amazeui-touch/blob/d002b8d04e5317a902d48b0226c95c32bf189fa4/kitchen-sink/components/App.js#L17-L25
- https://github.com/amazeui/amazeui-touch/blob/d002b8d04e5317a902d48b0226c95c32bf189fa4/kitchen-sink/pages/Default.js#L37-L41

Amaze UI Touch 没有实现自己的 View 管理器，目前的切换效果都是基于 React Router 的，搞懂 React Router 的工作原理，加上 ReactCSSTransitionGroup，基本上也就掌握如何实现不同的切换效果了。

细节在 https://github.com/amazeui/amazeui-touch/issues/76#issuecomment-230203002 里面已经做过描述，也可以看 React Router 的例子 https://github.com/reactjs/react-router/tree/master/examples/animations 。

**Comment by kdenz** [comment]
@minwe 好的 谢谢！
