### ISSUE TITLE
两个没影响运行但无端的报错

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#94]
1. 
![image](https://cloud.githubusercontent.com/assets/12795428/16987643/ee49cafc-4ebf-11e6-98ee-e9a2a3e221ff.png)
因为是在render里面，所以active=true 会报错，但active="true" 却又报不是boolean，实际却不影响运行

2.
![image](https://cloud.githubusercontent.com/assets/12795428/16987651/f929c404-4ebf-11e6-8a5b-91dfddf6a131.png)
就是放了个div进去

**Comment by minwe** [comment]
这不叫「无端报错」，警告信息已经说明了传入的属性类型与规定的不符。

第一个问题自己去看 JSX 语法 吧。
