### ISSUE TITLE
请问有 Field type="range" 的使用示例吗？

### ISSUE THREAD

**Issue by jdneo** [amazeui/amazeui-touch#95]
Thanks!

**Comment by minwe** [comment]
你需要什么示例？

和普通的 `input` 没什么区别，都是使用 `onChange` 这类标准事件接口添加事件处理器。

**Comment by jdneo** [comment]
哈哈，不好意思我刚接触前端，本来是想看看如何把range的值显示出来的，现在搞定了，不好意思打扰啦。
