### ISSUE TITLE
npm install 执行时报许多过时 warning, 

### ISSUE THREAD

**Issue by leegtang** [amazeui/amazeui-touch#96]
please update as soon as possible.

**Comment by minwe** [comment]
你说的「过时的 warning」是指这些？

![2016-07-26 8 50 28](https://cloud.githubusercontent.com/assets/4370770/17122430/10b5dd5e-530e-11e6-9b5c-e961584d36b3.png)

这些都是一些开发依赖的模块的问题，需要他们自己升级解决，对开发没有什么影响。
