### ISSUE TITLE
如何在使用Form的时候，手机键盘不会遮挡Form？

### ISSUE THREAD

**Issue by kdenz** [amazeui/amazeui-touch#97]
就是一打字的时候，可以令Form自动上移到键盘上面吗？谢谢

**Comment by minwe** [comment]
iOS 上是会自动往上滚动的，不知道你 Android 上如何。

两个方式：

- A：不要使用 `<Container>`，使用文档的滚动条应该就不会有这样的问题了；
- B：监听表单元素的 `focus` 事件，根据表单的元素的位置滚动容器。
